# Generated by Django 5.0.7 on 2024-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=43)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=54)),
            ],
        ),
    ]
