# Generated by Django 5.0.6 on 2024-05-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('work', models.CharField(max_length=33)),
                ('personality', models.CharField(max_length=44)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
