# Generated by Django 5.0.6 on 2024-05-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attender1',
            fields=[
                ('contactinfo1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo1')),
                ('work', models.CharField(max_length=33)),
                ('personality', models.CharField(max_length=44)),
            ],
            bases=('testapp.contactinfo1',),
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('contactinfo1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo1')),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=140)),
            ],
            bases=('testapp.contactinfo1',),
        ),
    ]
